sequenceDiagram
Note left of Browser: (The page is loaded the first time)
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/notes
Server-->> Browser: HTML-code
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
Server-->> Browser: main.css
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.js
Server-->> Browser: main.js
Note over Browser: browser starts executing js-code that requests JSON data from server
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
Server-->> Browser: [{content: "", date: "2022-12-13T07:04:45.163Z"},..]
Note over Browser: browser executes the event handler that renders notes to display
Note left of Browser: User creates a new note on the page
Browser->>Server: HTTP POST https://studies.cs.helsinki.fi/exampleapp/new_note
Note over Browser: The string inserted to the form is sent in the body of the POST request
Server-->> Browser: HTTP status code 302
Note over Server: server asks the browser to reload the page
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/notes
Server-->> Browser: HTML-code
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
Server-->> Browser: main.css
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.js
Server-->> Browser: main.js
Note over Browser: browser starts executing js-code that JSON data from server
Browser->>Server: HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
Server-->> Browser: [{content: "", date: "2022-12-13T07:04:45.163Z"},..]
Note over Browser: browser executes the event handler that renders notes to display with the note added

