### add a post without a token
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV1c2lrw6R5dHTDpGrDpHgiLCJpZCI6IjY0MzkxMWI5Y2QwYmYxNzQ3MDU4ZjAxZSIsImlhdCI6MTY4MjIyMjg2Mn0.-QU3hLWAEeY0kAnQRcLkNRVrjI2hQnmn934G77SWiU8

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
}
