
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "uusikäyttäjäx",
    "password": "sanasana"
}

### wrong password
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "uusikäyttäjäx",
    "password": "sanasanat"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "käyttäjäy",
    "password": "sanasala"
}