
### create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "uusikäyttäjäx",
    "name": "Uusi Käyttäjä X",
    "password": "sanasana"
}

### create another
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "käyttäjäy",
    "name": "Uusi Käyttäjä Y",
    "password": "sanasala"
}

### create a new user without username
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "name": "Uusi Käyttäjä Y",
    "password": "sanasana"
}

### create a user with already existing username
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "uusikäyttäjäx",
    "name": "Uusi Käyttäjä X",
    "password": "sanasana"
}

### create a user with a too short username
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "äx",
    "name": "Uusi Käyttäjä X",
    "password": "sanasana"
}

### create a user without password
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "uusikäyttäjäx",
    "name": "Uusi Käyttäjä X"
}

### create a user with too short password
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "uusikäyttäjäx",
    "name": "Uusi Käyttäjä X",
    "password": "sa"
}

### get all users
GET http://localhost:3003/api/users 
